/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RestEasyDemo;

public class Library {
    
    public static void main(String args[]) {
    
//     EntityManagerFactory emf = Persistence.createEntityManagerFactory("pu");
//    	
//   	 EntityManager em = emf.createEntityManager();
//   	
//   	 em.getTransaction().begin();  
//
//   	 em.getTransaction().commit();  
//     emf.close();  
//     em.close();  
    }
}
